---
title: "6252320_Assignment_3"
author: "Leon Debnath"
date: "02/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Assignment 3

Exercise 1

The Beta distribution $Beta(a, b)$ has the following Probability Density Function (PDF):
$$
f(x) =x^{a-1}(1-x)^{b-1}, \text{ for } 0< x <1,
$$

```{r}
a <- 5
b <- 2
beta <- function(x) x^(5-1) * (1-x)^(2-1)

set.seed(12345)
n = 10^5
X_rand <- runif(n, min=0, max=5)
Y_rand <- runif(n, min=0, max=5)

plot(X_rand, Y_rand, main='Uniform Distribution')

```
```{r}

beta_dist <- lapply(X_rand, beta) >= Y_rand/30

X_beta <- X_rand[beta_dist]
Y_beta <- Y_rand[beta_dist]

plot(X_beta, Y_beta, main='Beta Distribution')
```
The median of a value or function is calculated using
$$
median(f(x)) = \frac{\sum f(x)}{n}
$$
We can calculate a random sample within our distribution 
```{r}
median = sum(Y_beta)/length(Y_beta)
median
```


```{r}
X <- seq(0, 1, by = 0.02)
Y <- dbeta(X, shape1=a, shape2=b)
M = median(X, na.rm = FALSE)
M
plot(X,Y)
```